### ISSUE TITLE
Unable to run Docker image

### ISSUE THREAD

**Issue by mitar** [octoblu/meshblu#106]
Building a Docker image from current master, as explained in README, and running it, I get the following error:

```
Starting HTTP/HTTPS...createClient undefined {}
undefined is not a function TypeError: undefined is not a function
  at new Publisher (/usr/src/app/lib/Publisher.coffee:6:16)
  at Object.<anonymous> (/usr/src/app/lib/models/device.coffee:8:13)
  at Object.<anonymous> (/usr/src/app/lib/models/device.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/src/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
```

**Comment by slimjim2234** [comment]
Same issue here, it appears redis is now required in Publisher.coffee?
I thought meshblu could run without redis?

**Comment by iamruinous** [comment]
We temporarily made redis a requirement while we were replacing socket.io as the internal message bus. It should be optional again.
